server:
  port: 9010

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        email|sms-in-0:   # Binding name following our convention: in as input, 0 as starting index.
          destination: send-communication   # Queue name
          group: ${spring.application.name}   # we don't wont RabbitMQ to append some random values to our channel, destination and queue name.
        email|sms-out-0:  # Binding name following our convention: out as output, 0 as starting index.
          destination: communication-sent   # Exchange name
      kafka:
        binder:
          brokers:
            - localhost:9092  # For now, we have only one broker
